### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by holmesb** [vikaschoudhary16/sfc-device-plugin#5]
Issues and the readme refer to this video:
https://asciinema.org/a/UyzMDcSHB42eWrP0soiwPyhEM

which is now a broken link.  Anyone have a valid URL?

**Comment by neomantra** [comment]
@holmesb  This doesn't exactly answer your question, but I did watch the video before.  It's just a quick shell demo that installs the plugin and schedules some pods that affinitize to on SFC-enabled hosts.

K8S with Onload has been on my wishlist to explore more, so I'm happy to see other people interested.  I've not actually used this device plugin (or any one), but note that there's newer work based on this work:
 * https://github.com/solarflarecommunications/sfc-k8s-device-plugin
 * https://blog.openshift.com/the-path-to-cloud-native-trading-platforms/

The Kubernetes Docs itself point to this repo...
